# Generated by Django 4.2.25 on 2026-06-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='metadata',
        ),
    ]
