# Generated by Django 4.2.25 on 2026-07-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_metadata_alt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='gallery',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='assemblytour/gallery/media/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='media_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='assemblytour/gallery/thumbnails/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='thumbnail_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('youtube', 'YouTube')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
