# Generated by Django 6.0.1 on 2026-01-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='cover_image',
            field=models.ImageField(default='test.png', upload_to='assemblytour/packages/covers/'),
            preserve_default=False,
        ),
    ]
