# Generated by Django 6.0.1 on 2026-01-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('umrah', 'Umrah'), ('hajj', 'Hajj')], default='umrah', help_text='Category of the package (Umrah or Hajj)', max_length=10),
        ),
    ]
