# Generated by Django 6.0.1 on 2026-01-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(blank=True, help_text='Short description of the package', max_length=150),
        ),
    ]
