# Generated by Django 6.0.1 on 2026-01-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_type'),
    ]

    operations = [
    ]
