# Generated by Django 6.0.1 on 2026-01-19 18:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=accounts.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False),
        ),
    ]
