# Generated by Django 6.0.1 on 2026-01-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport_document',
            field=models.FileField(blank=True, help_text='Uploaded scan of the passport', null=True, upload_to='passports/'),
        ),
        migrations.AddField(
            model_name='user',
            name='yellow_card_document',
            field=models.FileField(blank=True, help_text='Uploaded scan of the yellow card', null=True, upload_to='yellow_cards/'),
        ),
    ]
