# Generated by Django 6.0.1 on 2026-01-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_passport_document_user_yellow_card_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passport_document',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yellow_card_document',
        ),
    ]
