# Generated by Django 4.2.25 on 2026-04-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_passport_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_approve_registrations',
            field=models.BooleanField(default=False, help_text='Can approve/reject registration steps in admin'),
        ),
    ]
