# Generated by Django 6.0.1 on 2026-01-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpost_author_blogpost_author_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.PositiveIntegerField(default=5, help_text='Minimum estimated read time for this blog in minutes'),
        ),
    ]
