# Generated by Django 6.0.1 on 2026-01-28 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcomment_parent_blogreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Comment', 'verbose_name_plural': 'Blog Comments'},
        ),
        migrations.AlterModelOptions(
            name='bloglike',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='blogreply',
            options={'ordering': ['created_at'], 'verbose_name': 'Blog Reply', 'verbose_name_plural': 'Blog Replies'},
        ),
        migrations.AlterModelOptions(
            name='blogviewer',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='user_image_url',
        ),
        migrations.RemoveField(
            model_name='blogreply',
            name='user_image_url',
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_comments', to='blog.blogcomment'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogreply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_replies', to='blog.blogcomment'),
        ),
        migrations.AlterField(
            model_name='blogreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
