# Generated by Django 6.0.1 on 2026-01-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.URLField(default='https://res.cloudinary.com/your_cloud_name/raw/upload/assembly-tour/placeholders/document-placeholder.pdf'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='upload_by',
            field=models.CharField(choices=[('user', 'User Only'), ('admin', 'Admin Only'), ('both', 'User and Admin')], default='user', max_length=10),
        ),
    ]
