# Generated by Django 6.0.1 on 2026-01-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecontent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencesection',
            name='image_one',
            field=models.ImageField(upload_to='assemblytour/home/experience/'),
        ),
        migrations.AlterField(
            model_name='experiencesection',
            name='image_two',
            field=models.ImageField(upload_to='assemblytour/home/experience/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to='assemblytour/home/hero_slides/'),
        ),
    ]
