# Generated by Django 6.0.1 on 2026-01-17 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal step key e.g. details, payment, documents', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Short title shown to users', max_length=100)),
                ('description', models.TextField(help_text='What the user needs to do in this step')),
                ('order', models.PositiveIntegerField(help_text='Step order (1, 2, 3...)', unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HajjRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hajj_registration', to=settings.AUTH_USER_MODEL)),
                ('completed_steps', models.ManyToManyField(blank=True, related_name='completed_by_users', to='registrations.registrationstep')),
                ('current_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='registrations.registrationstep')),
            ],
        ),
    ]
