# Generated by Django 6.0.1 on 2026-01-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationstep',
            name='action_type',
            field=models.CharField(choices=[('fill_form', 'Fill Form'), ('upload', 'Upload Files'), ('payment', 'Make Payment'), ('review', 'Review & Confirm'), ('approval', 'Admin Approval'), ('auto', 'System Generated')], default='auto', help_text='Type of action required in this step', max_length=20),
        ),
        migrations.AddField(
            model_name='registrationstep',
            name='data_scope',
            field=models.CharField(choices=[('user', 'User Profile'), ('registration', 'Hajj Registration'), ('documents', 'Documents'), ('payment', 'Payment'), ('visa', 'Visa'), ('hotel', 'Hotel'), ('flight', 'Flight')], default='registration', help_text='Which part of the system this step works on', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationstep',
            name='code',
            field=models.CharField(help_text='Internal step key (e.g. details, documents, payment)', max_length=50, unique=True),
        ),
    ]
