# Generated by Django 6.0.1 on 2026-01-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registrationstep_action_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hajjregistration',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Overall registration status', max_length=20),
        ),
    ]
