# Generated by Django 6.0.1 on 2026-01-29 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_hajjregistration_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hajjregistration',
            name='completed_steps',
            field=models.ManyToManyField(blank=True, related_name='completed_registrations', to='registrations.registrationstep'),
        ),
        migrations.AlterField(
            model_name='hajjregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationstep',
            name='action_type',
            field=models.CharField(choices=[('fill_form', 'Fill Form'), ('upload', 'Upload Files'), ('payment', 'Make Payment'), ('review', 'Review & Confirm'), ('approval', 'Admin Approval'), ('auto', 'System Generated')], default='auto', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationstep',
            name='code',
            field=models.CharField(help_text='Internal step key (e.g. account_setup, documents)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationstep',
            name='data_scope',
            field=models.CharField(choices=[('user', 'User Profile'), ('registration', 'Hajj Registration'), ('documents', 'Documents'), ('payment', 'Payment'), ('visa', 'Visa'), ('hotel', 'Hotel'), ('flight', 'Flight')], default='registration', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistrationStepReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason provided if the step was rejected', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_reviews', to='registrations.hajjregistration')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registration_steps', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='registrations.registrationstep')),
            ],
            options={
                'ordering': ['step__order'],
                'unique_together': {('registration', 'step')},
            },
        ),
    ]
