# Generated by Django 6.0.1 on 2026-01-29 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20260126_1432'),
        ('registrations', '0004_alter_hajjregistration_completed_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hajjregistration',
            name='hotel_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='international_passport',
            field=models.FileField(blank=True, null=True, upload_to='documents/passports/'),
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='packages.package'),
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='package_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='ticket_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='yellow_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/yellow_cards/'),
        ),
        migrations.AlterField(
            model_name='registrationstep',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationstep',
            name='data_scope',
            field=models.CharField(choices=[('user', 'User Profile'), ('registration', 'Hajj Registration'), ('documents', 'Documents'), ('payment', 'Payment'), ('hotel', 'Hotel'), ('flight', 'Flight')], default='registration', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationstep',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='registrationstep',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='registrationstep',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationstepreview',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
