# Generated by Django 6.0.1 on 2026-01-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_hajjregistration_hotel_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hajjregistration',
            options={},
        ),
        migrations.RemoveField(
            model_name='hajjregistration',
            name='hotel_info',
        ),
        migrations.RemoveField(
            model_name='hajjregistration',
            name='international_passport',
        ),
        migrations.RemoveField(
            model_name='hajjregistration',
            name='package_benefits',
        ),
        migrations.RemoveField(
            model_name='hajjregistration',
            name='ticket_info',
        ),
        migrations.RemoveField(
            model_name='hajjregistration',
            name='yellow_card',
        ),
    ]
