# Generated by Django 6.0.1 on 2026-01-30 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_alter_hajjregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hajjregistration',
            name='hotel_info',
            field=models.TextField(blank=True, help_text='Accommodation details', null=True),
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='package_benefits',
            field=models.TextField(blank=True, help_text='Specific benefits for this user', null=True),
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='passport_document',
            field=models.FileField(blank=True, null=True, upload_to='hajj/passports/'),
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='ticket_info',
            field=models.TextField(blank=True, help_text='Flight/Travel details', null=True),
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='yellow_card_document',
            field=models.FileField(blank=True, null=True, upload_to='hajj/yellow_cards/'),
        ),
        migrations.CreateModel(
            name='RegistrationAdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Visa Copy, Hotel Voucher', max_length=100)),
                ('file', models.FileField(upload_to='hajj_extra_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='registrations.hajjregistration')),
            ],
        ),
    ]
