# Generated by Django 6.0.1 on 2026-02-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_hajjregistration_hotel_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hajjregistration',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not_started'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
    ]
