# Generated by Django 4.2.25 on 2026-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_supportticket_supportticketreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('telegram', 'Telegram')], max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManasikGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('guidance_type', models.CharField(choices=[('ihram', 'Ihram Guide'), ('tawaf', "Tawaf & Sa'i"), ('dua', 'Dua & Prayers'), ('general', 'General Guide')], default='general', max_length=20)),
                ('content', models.TextField()),
                ('icon', models.CharField(default='📖', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
