# Generated by Django 4.2.25 on 2026-04-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_emergencycontact_manasikguidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hajjregistration',
            name='passport_document_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='yellow_card_document_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hajjregistration',
            name='passport_document',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hajjregistration',
            name='yellow_card_document',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
