# Generated by Django 4.2.25 on 2026-04-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_hajjregistration_passport_document_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hajjregistration',
            name='visa_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', help_text='Overall visa readiness status', max_length=20),
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='visa_status_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
