# Generated by Django 4.2.25 on 2026-04-07 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0013_hajjregistration_visa_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_travels', models.PositiveIntegerField(default=0)),
                ('in_progress_travels', models.PositiveIntegerField(default=0)),
                ('completed_travels', models.PositiveIntegerField(default=0)),
                ('failed_travels', models.PositiveIntegerField(default=0)),
                ('last_refresh', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Dashboard Stat',
                'verbose_name_plural': 'User Dashboard Stats',
            },
        ),
    ]
