# Generated by Django 4.2.25 on 2026-04-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_userdashboardstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hajjregistration',
            name='package_benefits',
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='journey_presence_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='journey_presence_status',
            field=models.CharField(choices=[('pre_travel', 'Awaiting Travel'), ('in_mecca', 'In Mecca'), ('arrived', 'Arrived'), ('did_not_arrive', 'Did Not Arrive')], default='pre_travel', help_text='Tracks traveler presence during and after the journey', max_length=20),
        ),
    ]
