# Generated by Django 4.2.25 on 2026-04-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_remove_hajjregistration_package_benefits_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveldocument',
            options={},
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='doc_type',
            field=models.CharField(choices=[('visa', 'Visa'), ('ticket', 'Flight Ticket'), ('hotel_voucher', 'Hotel Voucher')], default='visa', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='traveldocument',
            unique_together={('registration', 'doc_type')},
        ),
    ]
