# Generated by Django 4.2.25 on 2026-04-08 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0016_add_unique_travel_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Bank Transfer Receipt, Payment Proof', max_length=100)),
                ('file', models.FileField(upload_to='payment_details/')),
                ('description', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='registrations.hajjregistration')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_payment_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('registration', 'title')},
            },
        ),
    ]
