# Generated by Django 4.2.25 on 2026-04-11 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0020_add_travel_document_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hajjregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hajj_registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
