# Generated by Django 4.2.25 on 2026-04-11 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0021_alter_hajjregistration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hajjregistration',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation (required)', null=True),
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hajjregistration',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Admin who cancelled this registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
