# Generated by Django 4.2.25 on 2026-04-13 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0005_auto_20260126_1432'),
        ('registrations', '0022_hajjregistration_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_document', models.URLField(blank=True, max_length=500, null=True)),
                ('passport_document_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('yellow_card_document', models.URLField(blank=True, max_length=500, null=True)),
                ('yellow_card_document_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not_started'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('visa_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', help_text='Overall visa readiness status', max_length=20)),
                ('visa_status_notes', models.TextField(blank=True, null=True)),
                ('ticket_info', models.TextField(blank=True, help_text='Flight/Travel details', null=True)),
                ('hotel_info', models.TextField(blank=True, help_text='Accommodation details', null=True)),
                ('journey_presence_status', models.CharField(choices=[('pre_travel', 'Awaiting Travel'), ('in_mecca', 'In Destination'), ('arrived', 'Arrived'), ('did_not_arrive', 'Did Not Arrive')], default='pre_travel', help_text='Tracks traveler presence during and after the journey', max_length=20)),
                ('journey_presence_notes', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation (required)', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Admin who cancelled this registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_registrations', to=settings.AUTH_USER_MODEL)),
                ('completed_steps', models.ManyToManyField(blank=True, related_name='completed_registrations', to='registrations.registrationstep')),
                ('current_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='registrations.registrationstep')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='packages.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='registrations.registration'),
        ),
        migrations.AlterField(
            model_name='registrationadditionaldocument',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='registrations.registration'),
        ),
        migrations.AlterField(
            model_name='registrationstepreview',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_reviews', to='registrations.registration'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='registrations.registration'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_documents', to='registrations.registration'),
        ),
        migrations.DeleteModel(
            name='HajjRegistration',
        ),
    ]
