# Generated by Django 4.2.25 on 2026-04-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0023_rename_hajjregistration_to_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manasikguidance',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='manasik_icons/'),
        ),
    ]
