# Generated by Django 6.0.1 on 2026-01-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='body',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='head',
            new_name='question',
        ),
    ]
