# Generated by Django 4.2.25 on 2026-04-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='assemblytour/testimonials/'),
        ),
    ]
